# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_mainmustbuy_mainnav_mainshop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainmustbuy',
            old_name='tiackid',
            new_name='trackid',
        ),
        migrations.RenameField(
            model_name='mainnav',
            old_name='tiackid',
            new_name='trackid',
        ),
        migrations.RenameField(
            model_name='mainshop',
            old_name='tiackid',
            new_name='trackid',
        ),
        migrations.RenameField(
            model_name='mainwheel',
            old_name='tiackid',
            new_name='trackid',
        ),
    ]
