# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20180601_1643'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mainmustbuy',
            table='axf_mustbuy',
        ),
        migrations.AlterModelTable(
            name='mainnav',
            table='axf_nav',
        ),
        migrations.AlterModelTable(
            name='mainshop',
            table='axf_shop',
        ),
        migrations.AlterModelTable(
            name='mainwheel',
            table='axf_wheel',
        ),
    ]
